### ISSUE TITLE
Publish to DITA-OT plug-in registry

### ISSUE THREAD

**Issue by infotexture** [AntennaHouse/ah-wml#36]
Just heard Tony Graham's presentation on this plug-in at [DITA-OT Day](https://www.oxygenxml.com/events/2019/dita-ot_day.html), and it looks like it would be very useful to the community. 👍 

Please consider submitting this to the DITA-OT plug-in registry at https://www.dita-ot.org/plugins.

For an overview of the process, see [Publishing plug-ins to the registry](https://www.dita-ot.org/dev/topics/plugins-registry.html#plugin-registry__publishing-to-registry) in the DITA-OT documentation.

🙇

**Comment by ToshihikoMakita** [comment]
Thank you for your suggestion. I have been go away on trip in few days and returned just today. I will start registering work as soon as possible.

**Comment by ToshihikoMakita** [comment]
@infotexture 

I got the following error in testing. Are there any mistakes in `com.antennahouse.wml.json` ?

![2020-04-02-2](https://user-images.githubusercontent.com/1801890/78228193-589c1180-7509-11ea-81bd-48a0d9d4436d.png)

**Comment by ToshihikoMakita** [comment]
Solved! Changing the \[DITA-OT\]/config/configuration.properties to the following:

`registry = https://raw.githubusercontent.com/ToshihikoMakita/registry/addPlugin/`

**Comment by ToshihikoMakita** [comment]
Successfully merged!
https://github.com/dita-ot/registry/pull/76#pullrequestreview-387053504

**Comment by infotexture** [comment]
Excellent! Glad you were able to solve the problem, and thanks for submitting to the registry. 🙏
